#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Mar  5 22:33:05 2025

set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
remove_constraint  -logic -lcf "H:/PANGO_EDA/my_project/ddr_briey/first_try/first_try.lcf"
add_constraint "H:/PANGO_EDA/my_project/ddr_briey/ddr_briey_new.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
pnr 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "H:/PANGO_EDA/my_project/ddr_briey/first_try/first_try.lcf"
remove_constraint  -logic -lcf "H:/PANGO_EDA/my_project/ddr_briey/first_try/first_try.lcf"
remove_constraint  -logic -fdc "H:/PANGO_EDA/my_project/ddr_briey/ddr_briey_new.fdc"
add_constraint "H:/PANGO_EDA/my_project/ddr_briey/ddr_briey_new.fdc"
add_constraint "H:/PANGO_EDA/my_project/ddr_briey/ddr_briey_new.lcf"
remove_constraint  -logic -fdc "H:/PANGO_EDA/my_project/ddr_briey/ddr_briey_new.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module Briey
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
