
//
// Generated by Fabric Compiler (version 2022.1<build 99559>) at Sun Feb 23 15:34:03 2025
//
module led
(
    led,
    bot
);

(* PAP_IO_DIRECTION="INPUT", PAP_IO_LOC="K18", PAP_IO_VCCIO="1.2", PAP_IO_STANDARD="LVCMOS12", PAP_IO_NONE="TRUE", PAP_PORT_BUF_UNIT_TYPE="GTP_INBUF" *)    input bot;
(* PAP_IO_DIRECTION="OUTPUT", PAP_IO_LOC="B2", PAP_IO_VCCIO="1.2", PAP_IO_STANDARD="LVCMOS12", PAP_IO_DRIVE="2", PAP_IO_NONE="TRUE", PAP_IO_SLEW="SLOW", PAP_PORT_BUF_UNIT_TYPE="GTP_OUTBUF" *)    output led;

    wire \bot_ibuf/ntD ;
    wire \led_obuf/ntO ;
    wire nt_bot;
    wire nt_led;

    V_LUT5 /* N0/gateop_perm/FYA/FY */ #(
            .INIT(32'b00000000000000001111111111111111))
        \CLMA_214_296/FYA/FY  (
            .Y (nt_led),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (nt_bot));
	// LUT = ~I4 ;

    V_GRS GRS_INST (
            .GRS_N (1'b1));

    V_OBUF /* led_obuf/opit_0/obuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .SLEW_RATE("SLOW"), 
            .DRIVE_STRENGTH("8"))
        \IOBD_16_376/obuf  (
            .O (led),
            .I (\led_obuf/ntO ));
	// ../led.v:3

    V_IBUF /* bot_ibuf/opit_0/ibuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .TERM_DDR("ON"))
        \IOBS_LR_328_256/ibuf  (
            .O (\bot_ibuf/ntD ),
            .I (bot));
	// ../led.v:2

    V_MUX2 \IOL_19_374/MIPI_OUT/V_MUX2  (
            .Z (\led_obuf/ntO ),
            .I0 (nt_led),
            .I1 (1'b0),
            .SEL (1'b0));
	// ../led.v:3

    V_BUF \IOL_327_257/ntDI  (
            .Z (nt_bot),
            .I (\bot_ibuf/ntD ));
	// ../led.v:2


endmodule

